### ISSUE TITLE
How to use the tool

### ISSUE THREAD

**Issue by simoatze** [lzto/ProRace#1]
Hi,

I have been trying to use the tool but it does not list any dependencies and if I try to make some of the subfolders I get errors about missing files:

Makefile:7: ../Config/makefile.config: No such file or directory
Makefile:9: /Config/makefile.default.rules: No such file or directory
make: *** No rule to make target '/Config/makefile.default.rules'.  Stop.

is there any way to use the tool and reproduce your results?

Thanks.
Simone

**Comment by lzto** [comment]
I guess you have to install Intel Pin Tool first and setup correct environment variable.
Tong

**Comment by simoatze** [comment]
I have PIN tool. Got it, I'll try to setup the env variable correctly. Thanks!

**Comment by lzto** [comment]
should it be PIN_ROOT/source/tools/Config/makefile.config?

**Comment by simoatze** [comment]
Yes my bad, I missed that part. I'll give it a try.

**Comment by simoatze** [comment]
I was able to compile all tools:  branch_distance, olraced, pt_pin,  zpin.
What's the tool chain now? How do I use them?
